version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    tty: true
    ports:
      - "15672:15672"
      - "5672:5672"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq 

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq 
    
# networks:
#   default:
#     external:
#       name: myapp_default